package us.joshoconnor.FactPanda;

import java.util.Random;

/**
 * Created by joshuaoconnor on 10/13/14.
 */
public class FactBook {

    //Member variable (properties about the object)
    public String[] mFacts = {
            "A group of pugs is called a Grumble.",
            "Google's founders were willing to sell to Excite for under $1 million in 1999—but Excite turned them down.",
            "The famous Aaron Burr “Got Milk?” ad from 1993 was directed by Michael Bay.",
            "There was a third Apple founder. Ronald Wayne (pictured at home in 2010) sold his 10% stake for $800 in 1976.",
            "According to Amazon, the most highlighted Kindle books are the Bible, the Steve Jobs biography, and The Hunger Games.",
            "A California woman once tried to sue the makers of Cap'n Crunch because Crunch Berries contained 'no berries of any kind.'",
            "In a 2008 survey, 58% of British teens thought Sherlock Holmes was a real guy, while 20% thought Winston Churchill was not.",
            "At one point in the 1990s, 50% of all CDs produced worldwide were for AOL.",
            "Toy companies failed to duplicate the success of Theodore Roosevelt's teddy bear with William Taft's 'Billy Possum.'",
            "Nutella was invented during WWII, when an Italian pastry maker mixed hazelnuts into chocolate to extend his chocolate ration.",
            "In response to The Lorax, the forest products industry published Truax to teach kids the importance of logging.",
            "Tsutomu Yamaguchi was in Hiroshima for work when the first A-bomb hit, made it home to Nagasaki for the second, and lived to be 93.",
            "A British man changed his name to Tim Pppppppppprice to make it harder for telemarketers to pronounce.",
            "J.P. Morgan once offered $100,000 to anyone who could figure out why his face was so red. No one solved the mystery.",
            "Prairie dogs say hello with kisses.",
            "A 2009 search for the Loch Ness Monster came up empty. Scientists did find over 100,000 golf balls.",
            "New Mexico State's first graduating class in 1893 had only one student—and he was shot and killed before graduation.",
            "In the mid-1980s, Fergie of The Black Eyed Peas was the voice of Charlie Brown's sister Sally.",
            "Only one McDonald’s in the world has turquoise arches. Sedona, AZ thought yellow clashed with the natural red rock.",
            "The 50-star American flag was designed by an Ohio high school student for a class project. His teacher originally gave him a B–.",
            "According to the National Insurance Crime Bureau, the most commonly stolen vehicle in 2012 was the 1994 Honda Accord.",
            "After leaving office, Lyndon Johnson let his hair grow out.",
            "Crabs have their own version of the fist pump. Male crabs wave their claws in the air to attract females.",
            "Calvin Klein's Obsession for Men is used by researchers to attract animals to cameras in the wilderness.",
            "Chock Full o' Nuts coffee does not contain nuts. It's named for a chain of nut stores that the founder converted into coffee shops.",
            "Officials in Portland, Ore., drained 8 million gallons of water from a reservoir in 2011 because a buzzed 21-year-old peed in it",
            "There's a basketball court above the Supreme Court. It's known as the Highest Court in the Land.",
            "The medical term for ice cream headaches is sphenopalatine ganglioneuralgia.",
            "After Leonardo da Vinci's death, King Francis I of France hung the Mona Lisa in his bathroom.",
            "Redondo Beach, CA adopted the Goodyear Blimp as the city's official bird in 1983.",
            "In 2001, Beaver College changed its name to Arcadia in part because anti-porn filters blocked access to the school's website.",
            "Peeps Lip Balm is something that exists.",
            "Quentin Tarantino played an Elvis impersonator on The Golden Girls.",
            "Wendy's founder Dave Thomas dropped out of high school but picked up his GED in 1993. His GED class voted him Most Likely to Succeed.",
            "Sleeping through winter is hibernation, while sleeping through summer is estivation.",
            "In Qaddafi's compound, Libyan rebels found a photo album filled with pictures of Condoleezza Rice.",
            "Reed Hastings was inspired to start Netflix after racking up a $40 late fee on a VHS copy of Apollo 13.",
            "Marie Curie's notebooks are still radioactive. Researchers hoping to view them must sign a disclaimer.",
            "When three-letter airport codes became standard, airports that had been using two letters simply added an X.",
            "Just before the Nazis invaded Paris, H.A. and Margret Rey fled on bicycles. They were carrying the manuscript for Curious George.",
            "William McKinley was on the $500 bill, Grover Cleveland was on the $1,000, and James Madison was on the $5,000.",
            "In 1999, the U.S. government paid the Zapruder family $16 million for the film of JFK's assassination.\n",
            "Janis Joplin left $2,500 in her will for her friends to 'have a ball after I’m gone.'",
            "Fredric Baur invented the Pringles can. When he passed away in 2008, his ashes were buried in one.",
            "78% of NFL players are bankrupt two years after finishing their careers.",
            "60% of NBA players are bankrupt within five years of leaving the league.",
            "Male koalas have two penises. Female koalas have two vaginas.",
            "In Utah, it is against the law to fish from the back of a horse.",
            "If you put a can of Diet Coke in water, it floats. Regular Coca-Cola sinks.",
            "Apparently, if you eat a Polar Bear’s liver, you will die of a vitamin A overdose.",
            "The number one tire manufacturer in the world? LEGO.",
            "If you combine all the ants in the world, they’ll weigh about the same as if you combine all the people.",
            "The flamingo can only eat when its head is upside down.",
            "Because news traveled so slow back then, slaves in Texas didn’t know they were free for more than two months after Lincoln issued the Emancipation Proclamation.",
            "Talk about pressure. Female ferrets die if they can’t find a mate after going into heat.",
            "There are 18.6 million vacant homes in America. There are 3.1 million homeless people.",
            "Humans have had dogs as companions and workers for more than 14,000 years.",
            "A snail can sleep for more than three years at a time.",
            "The air quality of Mumbai is so bad, it’s equivalent to smoking 2½ packs of cigarettes a day.",
            "It is estimated that millions of trees are planted by forgetful squirrels.",
            "Cartographers used to include fake towns on their maps to catch forgers",
            "Australia has 10 times more camels than koalas",
            "Banging your head against a wall burns 150 calories an hour.",
            "In the UK, it is illegal to eat mince pies on Christmas Day!",
            "Pteronophobia is the fear of being tickled by feathers!",
            "When hippos are upset, their sweat turns red.",
            "A flock of crows is known as a murder.",
            "Facebook Addiction Disorder is a mental disorder identified by Psychologists.",
            "The average woman uses her height in lipstick every 5 years.",
            "Cherophobia is the fear of fun.",
            "Human saliva has a boiling point three times that of regular water.",
            "Heart attacks are more likely to happen on a Monday.",
            "There is a species of spider called the Hobo Spider.",
            "A baby spider is called a spiderling.",
            "You cannot snore and dream at the same time.",
            "A baby octopus is about the size of a flea when it is born.",
            "In Uganda, 50% of the population is under 15 years of age.",
            "Hitler’s mother considered abortion but the doctor persuaded her to keep the baby",
            "Recycling one glass jar saves enough energy to watch TV for 3 hours.",
            "Catfish are the only animals that naturally have an odd number of whiskers.",
            "Facebook, Skype and Twitter are all banned in China.",
            "95% of people text things they could never say in person.",
            "The Titanic was the first ship to use the SOS signal.",
            "A small child could swim through the veins of a blue whale.",
            "Sea otters hold hands when they sleep so they don’t drift away from each other.",
            "A crocodile can’t poke its tongue out",
            "Bob Dylan’s real name is Robert Zimmerman.",
            "Nearly three percent of the ice in Antarctic glaciers is penguin urine.",
            "The French language has seventeen different words for ‘surrender’.",
            "About 8,000 Americans are injured by musical instruments each year.",
            "The Titanic was the first ship to use the SOS signal.",
            "Facebook, Skype and Twitter are all banned in China.",
            "Mosquito repellents don't repel. They hide you. The spray blocks the mosquito's sensors so they don't know you're there.",
            "Karoke means 'empty orchestra' in Japanese.",
            "Odontophobia is the fear of teeth.",
            "The king of hearts is the only king without a moustache.",
            "It took Leo Tolstoy six years to write 'War & Peace'",
            "Stressed is Desserts spelled backwards.",
            "The only real person to be a Pez head was Betsy Ross.",
            "When the University of Nebraska Cornhuskers play football at home, the stadium becomes the state’s third largest city.",
            "A dragonfly has a lifespan of 24 hours.",
            "A dime has 118 ridges around the edge.",
            "A goldfish has a memory span of three seconds.",
            "About three-quarters of fresh water usage in American households occurs in the bathroom.",
            "In 1835, the government in Sonora, Mexico, offer a bounty for native male scalps of 100 pesos each. Female scalps, on the other hand, would only fetch 50 pesos.",
            "Only a few species of piranha are carnivorous; most eat plant matter or insects.",
            "Giraffes have the highest blood pressure of any mammal.",
            "General Robert E. Lee and his horse were buried at Washington and Lee University.",
            "Ben Franklin's formal education ended at ten years old.",
            "Chad and Barbie Soper of Rockford, Michigan, have three kids. They were born on 08/08/08, 09/09/09, and 10/10/10.",
            "The guy featured in the NBA logo is former Laker Jerry West.",
            "Horseradish is a member of the mustard family and can count cauliflower, kale and brussels sprouts among its cousins.",
            "The peacock is actually the name of the male peafowl. The female is called a peahen.",
            "Robert Lincoln, son of President Lincoln, was saved from a nasty railroad accident by Edwin Booth. Edwin was the brother of Abraham Lincoln's assassin, John Wilkes Booth.",
            "In South Africa prior to 1985, it was illegal for individuals of European ancestry and non-European ancestry to marry one another.",
            "An estimated 15% to 20% of people who receive gift cards never redeem them.",
            "Lake Nicaragua is the only spot on Earth where freshwater sharks swim in their native habitat.",
            "Because of the number of creepy-crawlies that make their home in the rivers and streams of Alabama, it's sometimes referred to as 'The Lizard State.'",
            "The musical Cats was based on a book of poems by T.S. Eliot titled Old Possum's Book of Practical Cats.",
            "The poinsettia's red petals are actually leaves.",
            "In an average NFL football game there are only about 12 minutes of actual play time.",
            "Camels actually originated in North America.",
            "The lowest batting average to win a batting title was .301 by Carl Yastrzemski in 1968.",
            "Felines have thirty-two muscles in each ear which control intricate movements for directional hearing.",
            "Creedence Clearwater Revival has had seven songs hit #2 on the pop singles chart but has never scored a number one hit.",
            "The dots on dice and dominoes are called 'pips.'",
            "The third right arm of a male octopus is more than an arm - it’s his reproductive organ.",
            "The most shoplifted food item in the U.S. is candy.",
            "While they were in the White House, John & Abigail Adams had dogs named Satan & Juno.",
            "The 50 tallest mountains on Earth are all located in Asia.",
            "When Disneyland opened on July 17, 1955, the 110°F temperatures melted the asphalt on Main Street and caused many high-heeled shoes to become stuck in the pavement.",
            "Ostriches can run faster than horses.",
            "If you combine all the ants in the world, they’ll weigh about the same as if you combine all the people.",
            "Humans have had dogs as companions and workers for more than 14,000 years.",
            "78% of NFL players are bankrupt two years after finishing their careers.",
            "Female cats tend to be right pawed, while male cats are more often left pawed. Interestingly, left handed humans also tend to be male.",
            "Turritopsis nutricula, known as the immortal jellyfish, can go from a mature medusa jellyfish back to a polyp, essentially avoiding death.",
            "Donald Ducks middle name is Fauntleroy.",
            "Deer can't eat hay.",
            "A rat can last longer without water than a camel.",
            "Honey is the only food that doesn't spoil.",
            "Pearls melt in vinegar.",
            "A male emperor moth can smell a female emperor moth up to 7 miles away.",
            "The average person falls asleep in seven minutes.",
            "Starfish have no brains.",
            "A tiny amount of liquor on a scorpion will make it instantly go mad and sting itself to death.",
            "Leonardo Da Vinci invented scissors.",
            "The Hawaiian alphabet has 12 letters.",
            "Donald Duck comics were banned from Finland because he doesn't wear any pants.",
            "Jellyfish like salt water. A rainy season often reduces the jellyfish population by putting more fresh water into normally salty waters where they live.",
            "On average, dogs have better eyesight than humans, although not as colorful.",
            "The porpoise is second to man as the most intelligent animal on the planet.",
            "Ostriches are often not taken seriously. They can run faster than horses, and the males can roar like lions.",
            "A ball of glass will bounce higher than a ball of rubber. A ball of solid steel will bounce higher than one made entirely of glass.",
            "Every human spent about half an hour as a single cell.",
            "The porpoise is second to man as the most intelligent animal on the planet.",
            "Seals used for their fur get extremely sick when taken aboard ships.",
            "Sloths take two weeks to digest their food.",
            "In every episode of Seinfeld there is a Superman somewhere.",
            "Rats and horses can't vomit.",
            "The cigarette lighter was invented before the match.",
            "Guinea pigs and rabbits can't sweat.",
            "A duck's quack doesn't echo, and no one knows why.",
            "Hot water is heavier than cold.",
            "People say \"Bless you\" when you sneeze because when you sneeze,your heart stops for a mili-second.",
            "There is enough iron in your body to make a 2-inch nail.",
            "The United States is an older country than Germany.",
            "A shrimp's heart is in it's head.",
            "More than 50% of the people in the world have never made or received a telephone call.",
            "More tigers live in Texas compared to the rest of the world.",
            "If you sneeze too hard, you can fracture a rib.",
            "“Will Will Smith smith?” and “Will Smith will smith” are sentences that make complete sense.",
            "There is a basketball court on the top floor of the U.S. Supreme Court Building. It’s known as the “highest court in the land.”",
            "Horses are not able to breathe through their mouths.",
            "It is physically impossible for pigs to look up into the sky.",
            "A crocodile can't stick it's tongue out.",
            "Cambridge University is older than the Aztec and Inca empires.",
            "Chocolate milk was invented in Ireland",
            "The lint that collects in the bottom of your pockets has a name — gnurr.",
            "Crocodiles are more closely related to birds than to lizards.",
            "111,111,111 × 111,111,111 = 12,345,678,987,654,321.",
            "Butterflies taste with their feet.",
            "There are more public libraries than McDonald’s in the U.S.",
            "Calculus was derived years after Harvard was founded.",
            "Ketchup used to be sold as medicine",
            "The flamingo can only eat when its head is upside down.",
            "If you put a can of Diet Coke in water, it floats. Regular Coca-Cola sinks.",
            "The flamingo can only eat when its head is upside down.",
            "The number one tire manufacturer in the world? LEGO.",
            "The air quality of Mumbai is so bad, it’s equivalent to smoking 2½ packs of cigarettes a day.",
            "Giant pandas have evolved a unique “thumb” which they use to hold bamboo stalks. This thumb is actually a modified wrist bone.",
            "The average snowflake falls at about 3 mph.",
            "A snail can sleep for more than three years at a time.",
            "If brain cells were replaced, like skin or liver cells, scientists hypothesize we would lose our memories.",
            "Mosquito repellents don't repel. They hide you. The spray blocks the mosquito's sensors so they don't know you're there.",
            "California consumes more bottled water than any other product.",
            "The 57 on Heinz ketchup bottles represents the number of varieties of pickles the company once had.",
            "A jiffy is an actual time measurement equaling 1/100th of a second.",
            "A group of a dozen or more cows is called a 'flink.",
            "In Texas, it is illegal to graffiti someone's cow.",
            "The king of hearts is the only king without a moustache.",
            "1 in 5 of the world’s doctors are Russian.",
            "Kangaroos cannot hop backwards",
            "The Great White Shark can go up to three months between meals.",
            "Pigeons have been trained by the U.S. Coast Guard to spot lost people at sea.",
            "Cows give more milk when they listen to music.",
            "The blue whale's heart is the size of a small car.",
            "On average, a laptop uses half as much energy as a desktop computer.",
            "The most popular pet name in the United States is 'Max'.",
            "Pilates stretches your muscles, improving your posture and helping you appear taller.",
            "The nothingness of a black hole generates a sound in the key of B flat.",
            "A male firefly's light is twice as bright as a female's.",
            "Cats sleep 16 to 18 hours per day.",
            "American car horns beep in the tone of F.",
            "The Neanderthal's brain was bigger than yours is.",
            "Grapes are the most popular fruit in the world.",
            "Stressed is Desserts spelled backwards.",
            "Cats can hear ultrasound.",
            "7.5 million toothpicks can be created from a cord of wood.",
            "The elephant is the only animal with four knees.",
            "The biggest pig in recorded history weighed almost one ton.",
            "Cats have 2 sets of vocal cords: one for purring, and one for meowing.",
            "Olympic gold medals are actually made mostly of silver.",
            "Elephants are the only mammals that can't jump.",
            "You are born with 300 bones; by the time you are an adult you will have 206.",
            "It takes about 8 minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The state of Florida is bigger than England.",
            "Life fingerprints, everyone's tongue print is different.",
            "The beaver is the official animal of Canada.",
            "Some penguins can leap 2-3 meters out of the water.",
            "On average, it takes 66 days to form a new habit.",
            "All scorpions glow.",
            "In 1860, Abraham Lincoln grew a beard at the suggestion of an 11 year old girl.",
            "Indonesia is made up of more than 17,000 islands.",
            "Astronauts actually get taller when in space.",
            "Josh O'Connor is the developer of this app.",
            "More than 180 countries celebrate Earth Day together every April 22nd",
            "The Hawaiian alphabet only has 12 letters.",
            "Allodoxophobia is the fear of hearing the opinions of other people.",
            "Salvador Dali would wake himself up the moment he fell asleep to capture and paint surreal dream images.",
            "Your brain is more active when you are sleeping than when you are watching television.",
            "The skin that covers the tip of your elbows is called a wenis.",
            "The woodpecker can hammer wood up to 16 times per second.",
            "In the year 2000, Pope John Paul II was named an Honorary Harlem Globetrotter.",
            "Young beavers stay with their parents for the first two years of their lives before going out on their own.",
            "15% of the air you breathe in a subway station is human skin.",
            "The Chinese used fingerprints as a method of identification as far back as AD 700.",
            "The human eye can distinguish more shades of green than any color.",
            "Although oxygen gas is colorless, the liquid and solid forms of oxygen are blue.",
            "If you pour a handful of salt into a full glass of water, the water level will actually go down than overflowing the glass.",
            "Astronauts can grow up to 2 inches in space because of the lack of pressure put on the spine.",
            "There are more vacant houses than homeless people in the United States.",
            "Russia did not consider beer to be alcohol until 2011.  It was previously classified as a soft drink.",
            "Caterpillars almost completely liquify before morphing into butterflies.",
            "A teddy bear once killed 2,500 fishes at one time.  It clogged a drain at a hatchery in New Hampshire, preventing the fish from getting oxygen.",
            "The location of the world's tallest tree, 'Hyperion', is kept secret from all but a select few scientists.",
            "Vin Diesel's name is an anagram of 'I END LIVES'.",
            "Before beginning his movie career, Keanu Reeves worked as a manager in a pasta ship in Toronto, Canada.",
            "Iceland was the first country to legalize abortion in 1935.",
            "Lemons are more acidic than vinegar.",
            "An individual banana is called a finger.  A bunch of bananas is called a hand.",
            "'Strengths', at nine letters long, is the longest word in the English language with only one vowel.",
            "Gentoo penguins propose to their life mates with a pebble.",
            "Replacing your car's air filter can improve gas mileage by 10 percent.",
            "The pineapple is neither an apple or a pine.  It is, in fact, a large berry.",
            "Seals sleep only one and a half minutes at a time.",
            "It is estimated that the world's oceans contain 10 billion tons of gold.",
            "The aphid insect is born pregnant.",
            "Theodore Roosevelt had a pet bear while in office.",
            "Poison Ivy is not Ivy and Poison Oak is not an Oak.  They are both part of the Cashew family.",
            "The number sign # is called an octothorpe.",
            "Miami installed the first ATM for inline skaters.",
            "No world in the English language rhymes with month.",
            "Of all the trees in Australia, 75% are Eucalyptus.",
            "There are 18 different animal shapes in the animal cracker zoo.",
            "The average human produces 10,000 gallons of saliva in a lifetime.",
            "The first bike was called a hobbyhorse.",
            "Grizzly bears run as fast as the average horse.",
            "A ball of glass will bounce higher than a ball of rubber.",
            "In 2003, a 6-year-old from Naples, FL was ticketed for not having a permit for her lemonade stand.",
            "Antartica has as much ice as the Atlantic Ocean has water.",
            "If done perfectly, any Rubick's Cube combination can be solved in 17 turns.",
            "In Ancient Greece, throwing an apple to a woman was considered a marriage proposal.",
            "It is illegal in the United Kingdom to handle salmon in suspicious circumstances.",
            "Mammoths still walked the earth when the Great Pyramid was being built.",
            "Ants stretch when they wake up in the morning."};

    //Method (abilities: things the object can do, in this case, store facts
    public String getFact() {



        // The button was clicked, so update the fact label with new fact
        String fact = "";

        // Randomly select a fact
        Random randomGenerator = new Random(); //Construct a new Random number Generator
        int randomNumber = randomGenerator.nextInt(mFacts.length);  //.length gives us length of array, or how many items in aray


        //choose random item from facts array
        fact = mFacts[randomNumber];

        //return the Fun Fact.  return is a keyword which means I'm done with this method, here's the keyword
        return fact;
    }

}
